apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's https port.
    service.alpha.openshift.io/dependencies: '[{"name":"sso-postgresql","namespace":"","kind":"Service"}]'
  labels:
    application: sso
    template: sso-service
    xpaas: 1.3.2
  name: secure-sso
  namespace: ci
spec:
  ports:
  - port: 8443
  selector:
    deploymentConfig: sso
