apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The database server port.
  labels:
    application: sso
    component: database
    template: sso-service
    xpaas: 1.3.2
  name: sso-postgresql
  namespace: ci
spec:
  ports:
  - port: 5432
  selector:
    deploymentConfig: sso-postgresql
