apiVersion: v1
imagePullSecrets:
- name: sso-service-account
kind: ServiceAccount
metadata:
  labels:
    application: sso
    template: sso-service
    xpaas: 1.3.2
  name: sso-service-account
  namespace: ci
secrets:
  - name: "sso-app-secret"
