apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2022-09-16T08:14:37Z"
  labels:
    build: sso
    template: sso-service
    xpaas: 1.3.2
  name: sso
  namespace: ci
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: sso:latest
    generation: 2
    name: latest
    referencePolicy:
      type: Source
