apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: sso-postgresql
    component: database
    template: sso-service
    xpaas: 1.3.2
  name: sso-postgresql
  namespace: ci
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deploymentConfig: sso-postgresql
  strategy:
    recreateParams:
      timeoutSeconds: 600
    type: Recreate
  template:
    metadata:
      labels:
        application: sso
        component: database
        deploymentConfig: sso-postgresql
      name: sso-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: coolstore
        - name: POSTGRESQL_PASSWORD
          value: coolstore
        - name: POSTGRESQL_DATABASE
          value: coolstore
        image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        name: sso-postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U coolstore -q -d coolstore -c 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 60
