apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: coolstore-gw
    demo: coolstore-microservice
    template: coolstore
  name: coolstore-gw
spec:
  host: coolstore-gw-coolstore.apps.cluster-b28bp-1.sandbox372.opentlc.com
  to:
    kind: Service
    name: coolstore-gw
    weight: 100
  wildcardPolicy: None
