apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2022-09-16T07:17:57Z"
  labels:
    demo: coolstore-microservice
    template: coolstore
  name: mongodb
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/mongodb-32-rhel7
    generation: 2
    name: "3.2"
    referencePolicy:
      type: Source
