apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    demo: coolstore-microservice
    template: coolstore
  name: web-ui
spec:
  host: web-ui-coolstore.apps.cluster-b28bp-1.sandbox372.opentlc.com
  to:
    kind: Service
    name: web-ui
    weight: 100
  wildcardPolicy: None
